services:
  # Service Web (Apache + PHP)
  web:
    build: .
    container_name: ecoride_web
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}

      - APP_ENV=${APP_ENV}
      - SITE_URL=${SITE_URL}
      - APP_TZ=${APP_TZ}

      - CONTACT_TO=${CONTACT_TO}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_DEBUG=${SMTP_DEBUG}

      - MAIL_FROM=${MAIL_FROM}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}

      - CLOUDINARY_URL=${CLOUDINARY_URL}
   
    networks:
      - ecoride_network

  # Service Base de données MySQL
  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"  # Port 3307 pour éviter conflits avec WAMP
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - ecoride_network

  # phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride_phpmyadmin
    ports:
      - "8091:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - ecoride_network

  # MongoDB service
  mongo:
    image: mongo:6
    container_name: ecoride_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecoride_network


  # Mongo Express for managing MongoDB
  mongo-express:
    image: mongo-express
    container_name: ecoride_mongo_ui
    ports:
      - "8092:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - ecoride_network

    # Mailpit (capture mails en local)
  mailpit:
    image: axllent/mailpit
    container_name: ecoride_mailpit
    ports:
      - "8093:8025"   # interface web
      - "1026:1025"   # SMTP
    networks:
      - ecoride_network

volumes:
  mysql_data:
  mongo_data:

networks:
  ecoride_network:
    driver: bridge

  