services:
  # Service Web (Apache + PHP)
  web:
    build: .
    container_name: ecoride_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ecoride
      - DB_USER=ecoride_user
      - DB_PASSWORD=ecoride_password

      - APP_ENV=dev

      - CONTACT_TO=maignaut.g@gmail.com

      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_SECURE=
      - SMTP_USER=
      - SMTP_PASS=
      
      - MAIL_FROM=no-reply@ecoride.local
      - MAIL_FROM_NAME=EcoRide
      - SMTP_DEBUG=2

      - CLOUDINARY_URL=${CLOUDINARY_URL}

    networks:
      - ecoride_network

  # Service Base de données MySQL
  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_password
    ports:
      - "3307:3306"  # Port 3307 pour éviter conflits avec WAMP
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - ecoride_network

  # phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ecoride_user
      PMA_PASSWORD: ecoride_password
      PMA_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - ecoride_network

  # MongoDB service
  mongo:
    image: mongo:6
    container_name: ecoride_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecoride_network


  # Mongo Express for managing MongoDB
  mongo-express:
    image: mongo-express
    container_name: ecoride_mongo_ui
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - ecoride_network

    # Mailpit (capture mails en local)
  mailpit:
    image: axllent/mailpit
    container_name: ecoride_mailpit
    ports:
      - "8025:8025"   # interface web
      - "1025:1025"   # SMTP
    networks:
      - ecoride_network

volumes:
  mysql_data:
  mongo_data:

networks:
  ecoride_network:
    driver: bridge

  